#!/usr/bin/env bash
# Refreshes app/src/main/res/raw/blocklist.txt from its two upstream lists.
#
#   oisd small        https://oisd.nl               GPL-3.0  low-breakage base
#   HaGeZi Pop-Up Ads https://github.com/hagezi/dns-blocklists  GPL-3.0  pop-under networks
#
# Both are "domain + all subdomains" lists. The output is one lowercase domain per line under a
# `#` header that BlockList parses for the Settings attribution dialog. Run from anywhere; needs
# curl, sort, grep, sed. Fails rather than writing a suspiciously small list.
set -euo pipefail
export LC_ALL=C

cd "$(dirname "$0")/.."
OUT=app/src/main/res/raw/blocklist.txt
UA="mrowser-blocklist-updater (+https://github.com/m-salehi-v/mrowser)"
OISD_URL="https://small.oisd.nl/domainswild2"
HAGEZI_URL="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/popupads-onlydomains.txt"
MIN_ENTRIES=50000

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

fetch() {
  curl -fsSL --retry 3 --retry-delay 5 -A "$UA" "$1" -o "$2"
  [ -s "$2" ] || { echo "empty download: $1" >&2; exit 1; }
}

# Comments and blanks out, lowercase, strip "*." and trailing dots and any whitespace, keep
# only lines that look like a domain (has a dot, no path).
clean() {
  grep -v '^[#!]' "$1" \
    | tr 'A-Z' 'a-z' \
    | sed -e 's/[[:space:]]//g' -e 's/^\*\.//' -e 's/^\.//' -e 's/\.$//' \
    | grep '\.' \
    | grep -v '/' \
    | grep -v '^$'
}

fetch "$OISD_URL" "$TMP/oisd.txt"
fetch "$HAGEZI_URL" "$TMP/hagezi.txt"

clean "$TMP/oisd.txt" | sort -u > "$TMP/oisd.clean"
clean "$TMP/hagezi.txt" | sort -u > "$TMP/hagezi.clean"
sort -u "$TMP/oisd.clean" "$TMP/hagezi.clean" > "$TMP/union"

OISD_N=$(wc -l < "$TMP/oisd.clean" | tr -d ' ')
HAGEZI_N=$(wc -l < "$TMP/hagezi.clean" | tr -d ' ')
TOTAL=$(wc -l < "$TMP/union" | tr -d ' ')
OISD_VER=$( { grep -m1 -i '^# Version:' "$TMP/oisd.txt" || true; } | sed 's/^# [Vv]ersion:[[:space:]]*//' | tr -d '\r')

if [ "$TOTAL" -lt "$MIN_ENTRIES" ]; then
  echo "only $TOTAL entries after cleaning (expected >= $MIN_ENTRIES); refusing to write" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
{
  echo "# mrowser block list - generated by scripts/update-blocklist.sh, do not edit by hand"
  echo "# generated: $(date -u +%Y-%m-%d)"
  echo "# source: oisd small | $OISD_URL | GPL-3.0 | $OISD_N entries | version ${OISD_VER:-unknown}"
  echo "# source: HaGeZi Pop-Up Ads | $HAGEZI_URL | GPL-3.0 | $HAGEZI_N entries"
  echo "# entries: $TOTAL"
  cat "$TMP/union"
} > "$OUT"

echo "wrote $OUT: $TOTAL domains (oisd $OISD_N, hagezi $HAGEZI_N)"
